### ISSUE TITLE
No Data received 

### ISSUE THREAD

**Issue by grackmczack** [RalphRathmann/WP-C19Ampel#1]
Hi,

tried to use the plugin but the retrieved data is not ne correct response. 
look like a problem with cloudfront?!
response data is:
array(6) { ["headers"]=> object(Requests_Utility_CaseInsensitiveDictionary)#11435 (1) { ["data":protected]=> array(22) { ["content-type"]=> string(25) "text/plain; charset=utf-8" ["content-length"]=> string(2) "97" ["cache-control"]=> string(35) "public, max-age=3600, s-maxage=3600" ["content-encoding"]=> string(2) "br" ["last-modified"]=> string(29) "Fri, 03 Sep 2021 01:47:53 GMT" ["etag"]=> string(16) "sd140_-793739716" ["server"]=> string(18) "Microsoft-IIS/10.0" ["x-arcgis-trace-id"]=> string(32) "c838b8bcad9e0644a36daed6c355505c" ["x-esri-query-readonly-replica"]=> string(4) "true" ["x-esri-query-request-units"]=> string(1) "2" ["x-esri-tiles-basic-query-mode"]=> string(4) "true" ["x-esri-tiles-basic-query-type"]=> string(5) "Basic" ["x-arcgis-correlation-id"]=> string(55) "00-c838b8bcad9e0644a36daed6c355505c-c40adcd3a05b1c45-00" ["x-arcgis-instance"]=> string(14) "MTSDS_Web_IN_0" ["strict-transport-security"]=> string(16) "max-age=63072000" ["access-control-allow-origin"]=> string(1) "*" ["date"]=> string(29) "Fri, 03 Sep 2021 11:04:39 GMT" ["x-cache"]=> string(19) "Hit from cloudfront" ["via"]=> string(64) "1.1 58c21e16c9e093deb494fbb4de260efa.cloudfront.net (CloudFront)" ["x-amz-cf-pop"]=> string(8) "FRA56-C1" ["x-amz-cf-id"]=> string(56) "Zdf0fY7G5wvdfBVNmmrtSeCh73ORuIgYls4azgScJ7rIWE9r60AQhA==" ["age"]=> string(4) "2824" } } ["body"]=> string(131) "{"objectIdFieldName":"OBJECTID","uniqueIdField":{"name":"OBJECTID","isSystemMaintained":true},"globalIdFieldName":"","features":[]}" ["response"]=> array(2) { ["code"]=> int(200) ["message"]=> string(2) "OK" } ["cookies"]=> array(0) { } ["filename"]=> NULL ["http_response"]=> object(WP_HTTP_Requests_Response)#11456 (5) { ["response":protected]=> object(Requests_Response)#11468 (10) { ["body"]=> string(131) "{"objectIdFieldName":"OBJECTID","uniqueIdField":{"name":"OBJECTID","isSystemMaintained":true},"globalIdFieldName":"","features":[]}" ["raw"]=> string(1036) "HTTP/1.1 200 OK Content-Type: text/plain; charset=utf-8 Content-Length: 97 Connection: close Cache-Control: public, max-age=3600, s-maxage=3600 Content-Encoding: br Last-Modified: Fri, 03 Sep 2021 01:47:53 GMT ETag: sd140_-793739716 Server: Microsoft-IIS/10.0 X-ArcGIS-Trace-Id: c838b8bcad9e0644a36daed6c355505c x-esri-query-readonly-replica: true x-esri-query-request-units: 2 x-esri-tiles-basic-query-mode: true x-esri-tiles-basic-query-type: Basic X-ArcGIS-Correlation-Id: 00-c838b8bcad9e0644a36daed6c355505c-c40adcd3a05b1c45-00 X-ArcGIS-Instance: MTSDS_Web_IN_0 Strict-Transport-Security: max-age=63072000 Access-Control-Allow-Origin: * Date: Fri, 03 Sep 2021 11:04:39 GMT X-Cache: Hit from cloudfront Via: 1.1 58c21e16c9e093deb494fbb4de260efa.cloudfront.net (CloudFront) X-Amz-Cf-Pop: FRA56-C1 X-Amz-Cf-Id: Zdf0fY7G5wvdfBVNmmrtSeCh73ORuIgYls4azgScJ7rIWE9r60AQhA== Age: 2824 {"objectIdFieldName":"OBJECTID","uniqueIdField":{"name":"OBJECTID","isSystemMaintained":true},"globalIdFieldName":"","features":[]}" ["headers"]=> object(Requests_Response_Headers)#11466 (1) { ["data":protected]=> array(22) { ["content-type"]=> array(1) { [0]=> string(25) "text/plain; charset=utf-8" } ["content-length"]=> array(1) { [0]=> string(2) "97" } ["cache-control"]=> array(1) { [0]=> string(35) "public, max-age=3600, s-maxage=3600" } ["content-encoding"]=> array(1) { [0]=> string(2) "br" } ["last-modified"]=> array(1) { [0]=> string(29) "Fri, 03 Sep 2021 01:47:53 GMT" } ["etag"]=> array(1) { [0]=> string(16) "sd140_-793739716" } ["server"]=> array(1) { [0]=> string(18) "Microsoft-IIS/10.0" } ["x-arcgis-trace-id"]=> array(1) { [0]=> string(32) "c838b8bcad9e0644a36daed6c355505c" } ["x-esri-query-readonly-replica"]=> array(1) { [0]=> string(4) "true" } ["x-esri-query-request-units"]=> array(1) { [0]=> string(1) "2" } ["x-esri-tiles-basic-query-mode"]=> array(1) { [0]=> string(4) "true" } ["x-esri-tiles-basic-query-type"]=> array(1) { [0]=> string(5) "Basic" } ["x-arcgis-correlation-id"]=> array(1) { [0]=> string(55) "00-c838b8bcad9e0644a36daed6c355505c-c40adcd3a05b1c45-00" } ["x-arcgis-instance"]=> array(1) { [0]=> string(14) "MTSDS_Web_IN_0" } ["strict-transport-security"]=> array(1) { [0]=> string(16) "max-age=63072000" } ["access-control-allow-origin"]=> array(1) { [0]=> string(1) "*" } ["date"]=> array(1) { [0]=> string(29) "Fri, 03 Sep 2021 11:04:39 GMT" } ["x-cache"]=> array(1) { [0]=> string(19) "Hit from cloudfront" } ["via"]=> array(1) { [0]=> string(64) "1.1 58c21e16c9e093deb494fbb4de260efa.cloudfront.net (CloudFront)" } ["x-amz-cf-pop"]=> array(1) { [0]=> string(8) "FRA56-C1" } ["x-amz-cf-id"]=> array(1) { [0]=> string(56) "Zdf0fY7G5wvdfBVNmmrtSeCh73ORuIgYls4azgScJ7rIWE9r60AQhA==" } ["age"]=> array(1) { [0]=> string(4) "2824" } } } ["status_code"]=> int(200) ["protocol_version"]=> float(1.1) ["success"]=> bool(true) ["redirects"]=> int(0) ["url"]=> string(310) "https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?where=OBJECTID=0&outFields=OBJECTID,GEN,BEZ,BL,cases,deaths,cases_per_population,cases7_per_100k,cases7_lk,death7_lk,cases7_bl_per_100k,cases7_bl,death7_bl,last_update&returnGeometry=false&outSR=&f=json" ["history"]=> array(0) { } ["cookies"]=> object(Requests_Cookie_Jar)#11432 (1) { ["cookies":protected]=> array(0) { } } } ["filename":protected]=> NULL ["data"]=> NULL ["headers"]=> NULL ["status"]=> NULL } }

**Comment by grackmczack** [comment]
this issue isn't an issue any more. you have to fill Landkreis-ID with a value other than Zero.

**Comment by RalphRathmann** [comment]
> Hi,
> 
> tried to use the plugin but the retrieved data is not ne correct response.
> look like a problem with cloudfront?!
> response data is:
> array(6) { ["headers"]=> object(Requests_Utility_CaseInsensitiveDictionary)#11435 (1) { ["data":protected]=> array(22) { ["content-type"]=> string(25) "text/plain; charset=utf-8" ["content-length"]=> string(2) "97" ["cache-control"]=> string(35) "public, max-age=3600, s-maxage=3600" ["content-encoding"]=> string(2) "br" ["last-modified"]=> string(29) "Fri, 03 Sep 2021 01:47:53 GMT" ["etag"]=> string(16) "sd140_-793739716" ["server"]=> string(18) "Microsoft-IIS/10.0" ["x-arcgis-trace-id"]=> string(32) "c838b8bcad9e0644a36daed6c355505c" ["x-esri-query-readonly-replica"]=> string(4) "true" ["x-esri-query-request-units"]=> string(1) "2" ["x-esri-tiles-basic-query-mode"]=> string(4) "true" ["x-esri-tiles-basic-query-type"]=> string(5) "Basic" ["x-arcgis-correlation-id"]=> string(55) "00-c838b8bcad9e0644a36daed6c355505c-c40adcd3a05b1c45-00" ["x-arcgis-instance"]=> string(14) "MTSDS_Web_IN_0" ["strict-transport-security"]=> string(16) "max-age=63072000" ["access-control-allow-origin"]=> string(1) "_" ["date"]=> string(29) "Fri, 03 Sep 2021 11:04:39 GMT" ["x-cache"]=> string(19) "Hit from cloudfront" ["via"]=> string(64) "1.1 58c21e16c9e093deb494fbb4de260efa.cloudfront.net (CloudFront)" ["x-amz-cf-pop"]=> string(8) "FRA56-C1" ["x-amz-cf-id"]=> string(56) "Zdf0fY7G5wvdfBVNmmrtSeCh73ORuIgYls4azgScJ7rIWE9r60AQhA==" ["age"]=> string(4) "2824" } } ["body"]=> string(131) "{"objectIdFieldName":"OBJECTID","uniqueIdField":{"name":"OBJECTID","isSystemMaintained":true},"globalIdFieldName":"","features":[]}" ["response"]=> array(2) { ["code"]=> int(200) ["message"]=> string(2) "OK" } ["cookies"]=> array(0) { } ["filename"]=> NULL ["http_response"]=> object(WP_HTTP_Requests_Response)#11456 (5) { ["response":protected]=> object(Requests_Response)#11468 (10) { ["body"]=> string(131) "{"objectIdFieldName":"OBJECTID","uniqueIdField":{"name":"OBJECTID","isSystemMaintained":true},"globalIdFieldName":"","features":[]}" ["raw"]=> string(1036) "HTTP/1.1 200 OK Content-Type: text/plain; charset=utf-8 Content-Length: 97 Connection: close Cache-Control: public, max-age=3600, s-maxage=3600 Content-Encoding: br Last-Modified: Fri, 03 Sep 2021 01:47:53 GMT ETag: sd140_-793739716 Server: Microsoft-IIS/10.0 X-ArcGIS-Trace-Id: c838b8bcad9e0644a36daed6c355505c x-esri-query-readonly-replica: true x-esri-query-request-units: 2 x-esri-tiles-basic-query-mode: true x-esri-tiles-basic-query-type: Basic X-ArcGIS-Correlation-Id: 00-c838b8bcad9e0644a36daed6c355505c-c40adcd3a05b1c45-00 X-ArcGIS-Instance: MTSDS_Web_IN_0 Strict-Transport-Security: max-age=63072000 Access-Control-Allow-Origin: * Date: Fri, 03 Sep 2021 11:04:39 GMT X-Cache: Hit from cloudfront Via: 1.1 58c21e16c9e093deb494fbb4de260efa.cloudfront.net (CloudFront) X-Amz-Cf-Pop: FRA56-C1 X-Amz-Cf-Id: Zdf0fY7G5wvdfBVNmmrtSeCh73ORuIgYls4azgScJ7rIWE9r60AQhA== Age: 2824 {"objectIdFieldName":"OBJECTID","uniqueIdField":{"name":"OBJECTID","isSystemMaintained":true},"globalIdFieldName":"","features":[]}" ["headers"]=> object(Requests_Response_Headers)#11466 (1) { ["data":protected]=> array(22) { ["content-type"]=> array(1) { [0]=> string(25) "text/plain; charset=utf-8" } ["content-length"]=> array(1) { [0]=> string(2) "97" } ["cache-control"]=> array(1) { [0]=> string(35) "public, max-age=3600, s-maxage=3600" } ["content-encoding"]=> array(1) { [0]=> string(2) "br" } ["last-modified"]=> array(1) { [0]=> string(29) "Fri, 03 Sep 2021 01:47:53 GMT" } ["etag"]=> array(1) { [0]=> string(16) "sd140_-793739716" } ["server"]=> array(1) { [0]=> string(18) "Microsoft-IIS/10.0" } ["x-arcgis-trace-id"]=> array(1) { [0]=> string(32) "c838b8bcad9e0644a36daed6c355505c" } ["x-esri-query-readonly-replica"]=> array(1) { [0]=> string(4) "true" } ["x-esri-query-request-units"]=> array(1) { [0]=> string(1) "2" } ["x-esri-tiles-basic-query-mode"]=> array(1) { [0]=> string(4) "true" } ["x-esri-tiles-basic-query-type"]=> array(1) { [0]=> string(5) "Basic" } ["x-arcgis-correlation-id"]=> array(1) { [0]=> string(55) "00-c838b8bcad9e0644a36daed6c355505c-c40adcd3a05b1c45-00" } ["x-arcgis-instance"]=> array(1) { [0]=> string(14) "MTSDS_Web_IN_0" } ["strict-transport-security"]=> array(1) { [0]=> string(16) "max-age=63072000" } ["access-control-allow-origin"]=> array(1) { [0]=> string(1) "_" } ["date"]=> array(1) { [0]=> string(29) "Fri, 03 Sep 2021 11:04:39 GMT" } ["x-cache"]=> array(1) { [0]=> string(19) "Hit from cloudfront" } ["via"]=> array(1) { [0]=> string(64) "1.1 58c21e16c9e093deb494fbb4de260efa.cloudfront.net (CloudFront)" } ["x-amz-cf-pop"]=> array(1) { [0]=> string(8) "FRA56-C1" } ["x-amz-cf-id"]=> array(1) { [0]=> string(56) "Zdf0fY7G5wvdfBVNmmrtSeCh73ORuIgYls4azgScJ7rIWE9r60AQhA==" } ["age"]=> array(1) { [0]=> string(4) "2824" } } } ["status_code"]=> int(200) ["protocol_version"]=> float(1.1) ["success"]=> bool(true) ["redirects"]=> int(0) ["url"]=> string(310) "https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?where=OBJECTID=0&outFields=OBJECTID,GEN,BEZ,BL,cases,deaths,cases_per_population,cases7_per_100k,cases7_lk,death7_lk,cases7_bl_per_100k,cases7_bl,death7_bl,last_update&returnGeometry=false&outSR=&f=json" ["history"]=> array(0) { } ["cookies"]=> object(Requests_Cookie_Jar)#11432 (1) { ["cookies":protected]=> array(0) { } } } ["filename":protected]=> NULL ["data"]=> NULL ["headers"]=> NULL ["status"]=> NULL } }

Hi grackmczack,

did you install this plugin from the Official WordPress Plugin Directory?
No need to install it manually anymore.

Once You installed it the "WordPress-way", does this work?
Which WP-Version?
Which Country? (data are from german server for the german districts)
