### ISSUE TITLE
shortcode with objectid doesnt work

### ISSUE THREAD

**Issue by grackmczack** [RalphRathmann/WP-C19Ampel#2]
Hi,

did you forgot to implement it? no id gets a response. everytime only the response from the landkreis ID in the backend. the GET Parameters for URL to fetch the landkreis is working.

**Comment by RalphRathmann** [comment]
> Hi,
> 
> did you forgot to implement it? no id gets a response. everytime only the response from the landkreis ID in the backend. the GET Parameters for URL to fetch the landkreis is working.

Working example for Hamburg:
[https://www.rredv.net/corona-ampel/?landkreis=16](https://www.rredv.net/corona-ampel/?landkreis=16)

So did You call it this way?
Does the page exist? e.g. corona-ampel  and did you include the shortcode there?

**Comment by RalphRathmann** [comment]
since there is no answer, i guess, its working
